const LEGAL_BLOCKS = [
  {
    title: 'AI-Generated Content Disclaimer',
    text: 'PitchVoid uses artificial intelligence to organize and structure user-provided content. All outputs are generated based on information you provide. PitchVoid does not guarantee the accuracy, completeness, or suitability of any generated content for any specific purpose.\n\nYou are solely responsible for reviewing, editing, and verifying all content before use in any professional, personal, legal, financial, or medical context. PitchVoid outputs should not be treated as professional advice of any kind.',
  },
  {
    title: 'No Professional Advice',
    text: 'PitchVoid is not a substitute for professional consultation. Content generated for scenarios involving legal matters (tenant disputes, contracts), financial decisions (investments, salary negotiations), medical situations, or any regulated domain is provided for organizational purposes only and does not constitute legal, financial, medical, or professional advice. Consult a qualified professional for specific guidance.',
  },
  {
    title: 'Accuracy and Hallucination',
    text: 'While PitchVoid is designed to use only information you provide and not fabricate facts, AI systems may occasionally produce inaccurate, incomplete, or misleading content. Always verify important facts, figures, and claims in your output before relying on them.',
  },
  {
    title: 'Data and Privacy',
    text: 'Your inputs and generated outputs are stored securely on our servers to provide the service. We do not sell, share, or distribute your personal content to third parties. We do not use your content to train AI models. You may delete your data at any time by deleting individual projects or your entire account. For complete details, see our Privacy Policy.',
  },
  {
    title: 'Credits and Payments',
    text: 'Credits are non-transferable and are associated with your account. Each credit is consumed when an output is generated. Refining, practicing, and exporting existing outputs does not consume credits. Unused credits do not expire. Refunds for unused credits are available within 14 days of purchase. Used credits cannot be refunded as the service has been rendered.',
  },
  {
    title: 'Service Availability',
    text: "PitchVoid is provided on an 'as-is' and 'as-available' basis. We do not guarantee uninterrupted service. We reserve the right to modify features, pricing, or credit values with reasonable notice. Existing purchased credits will be honored regardless of pricing changes.",
  },
  {
    title: 'Limitation of Liability',
    text: 'To the maximum extent permitted by law, PitchVoid and its operators shall not be liable for any damages arising from your use of the service, including but not limited to the use of AI-generated content in professional, personal, or public settings. Your use of any generated content is at your own risk.',
  },
  {
    title: 'Intellectual Property',
    text: 'Content you input into PitchVoid remains yours. Content generated by PitchVoid based on your inputs is licensed to you for unlimited personal and commercial use. PitchVoid retains no ownership of your generated outputs.',
  },
  {
    title: 'Changes to Terms',
    text: 'We may update these terms from time to time. Continued use of PitchVoid after changes constitutes acceptance of the updated terms. Material changes will be communicated via email or in-app notification.',
  },
  {
    title: 'Contact',
    text: 'For questions, refund requests, or data deletion: support@pitchvoid.com',
  },
];

export default function LegalSection() {
  return (
    <section id="legal" className="max-w-[700px] mx-auto mt-20 sm:mt-28 px-4 sm:px-0 mb-10">
      <p className="text-[13px] uppercase tracking-[0.2em] text-foreground/30 mb-6 text-center">
        Legal
      </p>

      <div className="space-y-6">
        {LEGAL_BLOCKS.map((block, i) => (
          <div key={i}>
            <h3 className="text-[13px] font-medium text-foreground/40 mb-1.5">
              {block.title}
            </h3>
            <p className="text-[12px] leading-relaxed text-foreground/25 whitespace-pre-line">
              {block.text}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
}
